package net.sachau.solitude.engine;

public enum Event {
    ERROR,
    NEXT_TURN,
    PLAYER_OPEN_DOOR_DONE,
    PLAYER_USED,
    NEXT_TURN_GUI, UPDATE_DOOR, PLAYER_DIED, PLAYER_WON, PLAYER_MISSION_FAILED, PLAYER_UPDATE_ITEMS, PLAYER_UPDATE, STATUS_BAR_UPDATE, PLAYER_MOVE_DONE, TEXT_NODE, PLAYER_ATTACK_DONE
}
